# SITE SETUP
# Documentation: https://docs.hugoblox.com/

appearance:
  theme_day: minimal
  theme_night: cyberpunk  # More tech-focused dark theme
  font: minimal
  font_size: L
  # Custom CSS for tech theme
  custom_css:
    - custom.css

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: 'The University of Toledo'
    description: 'Abrar Hossain - HPC Researcher specializing in Edge Computing and Machine Learning'
    twitter: 'AbrarHoessain'

# Site header
header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: false
    show_day_night: true  # Enable dark mode toggle
    show_search: true
    highlight_active_link: true
    background: dark  # Dark navbar
    
# Site footer
footer:
  copyright:
    notice: '© {year} Abrar Hossain. Built with Hugo Blox Builder.'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Features
features:
  syntax_highlighter:
    theme_light: github-light
    theme_dark: dracula  # Cool dark theme for code
  math:
    enable: true
  privacy_pack:
    enable: true
  repository:
    url: 'https://github.com/AbrarHossainHimself/abrarhossainhimself.github.io'
    content_dir: content
    branch: main
  avatar:
    shape: circle
  comment:
    provider: ''
  search:
    provider: wowchemy
    algolia:
      show_logo: false
  map:
    provider: ''
    api_key: ''
    zoom: 15

# Extensions
extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: true